import { GraduationCap, Zap, Target, Download } from 'lucide-react';

export function WhyDevStudio() {
  const benefits = [
    {
      icon: Zap,
      title: 'Rapid Prototyping',
      description: 'Go from a concept to a functional web preview in seconds. Perfect for testing layout ideas quickly.'
    },
    {
      icon: GraduationCap,
      title: 'Transparent Source Code',
      description: 'No hidden logic. View the raw HTML, CSS, and JS generated by the AI in real-time to see how things are built.'
    },
    {
      icon: Download,
      title: 'Portable Projects',
      description: 'Your code isn\'t locked in. Use the export feature to take your files and host them anywhere you choose.'
    }
  ];

  return (
    <section className="py-20 px-6">
      <div className="container mx-auto">
        <h2 className="text-3xl font-bold text-white mb-12">Why DevStudio?</h2>
        
        <div className="grid md:grid-cols-3 gap-8">
          {benefits.map((benefit, index) => {
            const Icon = benefit.icon;
            return (
              <div key={index} className="flex gap-4">
                <div className="flex-shrink-0">
                  <div className="w-12 h-12 rounded-full bg-blue-600/10 flex items-center justify-center border border-blue-600/30">
                    <Icon className="w-6 h-6 text-blue-500" />
                  </div>
                </div>
                <div>
                  <h3 className="text-xl font-semibold text-white mb-2">{benefit.title}</h3>
                  <p className="text-slate-400">{benefit.description}</p>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
